#! /usr/bin/env python3
# coding: utf-8

import os
from flamewok.cli import cli
from flamewok import Form, check_type
import shutil

"""
Templars

first:
$ pip install flamewok

then:
- Copy this script in your ~/bin folder and create a ~/bin/templars_krak directory
- put your templates in the templar's Krak
- call this script from anywhere with '$ templars' and enjoy the time you win ;)

read the help:

$ templars --help

"""

filename = __file__.split("/")[-1]

what_so = f"""
'{filename}' is a tool that allows to use both folders and files as templates.

"""

BASE_DIR = os.path.abspath(os.path.dirname(__file__))
KRAK = os.path.join(BASE_DIR, "templars_krak")
templates_list = os.listdir(KRAK)

templates = {}

for i in range(1, len(templates_list)+1):
    templates[i] = templates_list[i-1]

def valid_entry(x):
    if not check_type(x.split(" ")[0], int):
        return False
    if len(x.split(" ")) > 2:
        return False
    if len(x.split(" ")) > 1:
        if x.split(" ")[1] != ".":
            return False
    if int(x.split(" ")[0]) >len(templates_list):
        return False
    return True

form_index = Form([
    ("index", "\nselect an index (0 to exit)",
    lambda x: valid_entry(x))
])


def copy_template(template):
    from_files = os.path.join(KRAK, template)
    if os.path.isdir(from_files):
        shutil.copytree(
            from_files, os.path.join(os.getcwd(), template))
    else:
        shutil.copyfile(from_files, os.path.join(os.getcwd(), template))


def copy_deployed(template):
    src = os.path.join(KRAK, template)
    files = [os.path.join(KRAK, template, file) for file in os.listdir(src)]
    for file in files:
        print(file)
        if os.path.isdir(file):
            print("[DIR]")
            shutil.copytree(
                file, os.path.join(os.getcwd(), file.split("/")[-1]))
        else:
            print("[file]")
            shutil.copyfile(file, os.path.join(os.getcwd(), file.split("/")[-1]))

    print("DEPLOY")


def display_template_form():
    response = form_index.ask()
    key = int(response.index.split(" ")[0])
    if "." in response.index.split(" ")[0:]:
        option = "."
    else:
        option = None

    if key <= 0:
        quit()
    else:
        return templates[key], option


def display_templates():
    for key in templates:
        index = str(key)
        from_files = os.path.join(KRAK, templates[key])
        if os.path.isdir(from_files):
            index += "*"
        description = f"{index:<3}: {templates[key]:<45}"
        print(description)
    print("\n*: [is a directory: add a space and dot after the index (eg:'1 .') to copy 'deployed']")
    template, option = display_template_form()
    print(f"copy {template}...")
    if os.path.isdir(os.path.join(KRAK, template)) and option == ".":
        copy_deployed(template)
    else:
        copy_template(template)
    print("Done.")


def open_krak():
    os.system(f"xdg-open {KRAK}")


def main():
    display_templates()



if __name__ == "__main__":

    cli.route(
        what_so,
        ("", main, "run -Templar's Krak- and let your templates rule !"),
        (["-h", "--help"], cli.help, "display this help"),
        ("open", open_krak, "open the templates's storage directory"),
        "",
        "ABOUT",
        "github here:",
        "https://github.com/byoso/templars_krak"
    )
